// src/app/(routes)/application/steps/DocumentsStep.tsx
import { useEffect, useState } from 'react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Alert, AlertDescription } from '@/components/ui/alert'
import { Button } from '@/components/ui/button'
import { Textarea } from '@/components/ui/textarea'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { useApplicationStore } from '@/stores/applicationStore'
import { FileText, MessageSquare, ChevronDown, ChevronUp, MoreVertical, File, X } from 'lucide-react'
import ClientTabs from './ClientTabs'
import DocumentUploadModal from '@/components/DocumentUploadModal'
import type { Condition, ConditionDocument } from '@/types/conditions'
import { generateDocumentId } from '@/lib/idGenerator'

// Condition Card Component matching the design
function ConditionCard({ condition, onUpload, onAddNote, onRemoveDocument, onStatusChange }: { 
  condition: Condition
  onUpload: (conditionId: string) => void
  onAddNote: (conditionId: string, note: string) => void
  onRemoveDocument: (conditionId: string, documentId: string) => void
  onStatusChange: (conditionId: string, status: 'pending' | 'in_progress' | 'completed') => void
}) {
  const [showAllActivity, setShowAllActivity] = useState(false)
  const [showAddNote, setShowAddNote] = useState(false)
  const [newNote, setNewNote] = useState('')

  const getStatusBadge = () => {
    switch (condition.status) {
      case 'pending':
        return <Badge className="bg-yellow-100 text-yellow-800 border-yellow-200">Pending</Badge>
      case 'in_progress':
        return <Badge className="bg-blue-100 text-blue-800 border-blue-200">In Progress</Badge>
      case 'completed':
        return <Badge className="bg-green-100 text-green-800 border-green-200">Completed</Badge>
      default:
        return <Badge className="bg-gray-100 text-gray-800 border-gray-200">Revision Requested</Badge>
    }
  }

  const formatDateTime = (dateString: string) => {
    const date = new Date(dateString)
    return date.toLocaleDateString('en-US', { 
      month: 'short', 
      day: 'numeric', 
      year: 'numeric',
      hour: 'numeric',
      minute: '2-digit',
      hour12: true,
      timeZoneName: 'short'
    })
  }

  const handleAddNote = () => {
    if (newNote.trim()) {
      onAddNote(condition.id, newNote.trim())
      setNewNote('')
      setShowAddNote(false)
    }
  }

  const formatFileSize = (bytes: number): string => {
    if (bytes === 0) return '0 Bytes'
    const k = 1024
    const sizes = ['Bytes', 'KB', 'MB', 'GB']
    const i = Math.floor(Math.log(bytes) / Math.log(k))
    return Math.round(bytes / Math.pow(k, i) * 100) / 100 + ' ' + sizes[i]
  }

  return (
    <Card className="mb-6 w-full">
      <CardContent className="p-6 pt-8">
        {/* Header */}
        <div className="flex items-start justify-between mb-4">
          <div className="flex-1">
            <div className="flex items-center gap-3 mb-2">
              <h3 className="text-xl font-semibold text-gray-900">{condition.title}</h3>
              {getStatusBadge()}
            </div>
            <p className="text-gray-700">{condition.description}</p>
          </div>
          <Button variant="ghost" size="sm" className="h-8 w-8 p-0">
            <MoreVertical className="h-4 w-4" />
          </Button>
        </div>

        {/* Uploaded Documents */}
        {condition.documents.length > 0 && (
          <div className="mb-4 border-t border-gray-200 pt-4">
            <div className="flex items-center gap-2 text-gray-900 font-semibold mb-3">
              <File className="h-4 w-4" />
              <span>Uploaded Documents ({condition.documents.length})</span>
            </div>
            <div className="space-y-2">
              {condition.documents.map((doc) => (
                <div
                  key={doc.id}
                  className="flex items-center justify-between p-3 bg-gray-50 rounded-lg"
                >
                  <div className="flex items-center gap-3 flex-1 min-w-0">
                    <FileText className="h-5 w-5 text-red-600 flex-shrink-0" />
                    <div className="flex-1 min-w-0">
                      <p className="text-sm font-medium text-gray-900 truncate">
                        {doc.name}
                      </p>
                      <p className="text-xs text-gray-500">
                        {formatFileSize(doc.size)} • Uploaded by {doc.uploadedBy} • {formatDateTime(doc.uploadedAt)}
                      </p>
                    </div>
                  </div>
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={() => onRemoveDocument(condition.id, doc.id)}
                    className="h-8 w-8 p-0 flex-shrink-0 hover:bg-red-100 hover:text-red-700"
                  >
                    <X className="h-4 w-4" />
                  </Button>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Activity Section - Only shown when expanded */}
        {showAllActivity && (
          <div className="border-t border-gray-200 pt-4 mb-4">
            <div className="flex items-center gap-2 text-gray-900 font-semibold mb-3">
              <MessageSquare className="h-4 w-4" />
              <span>Activity</span>
            </div>
            {condition.notes.length > 0 ? (
              <div className="space-y-3">
                {condition.notes.slice().reverse().map((note) => (
                  <div key={note.id} className="bg-gray-50 rounded-lg p-3">
                    <div className="flex items-center justify-between mb-1">
                      <span className="font-medium text-gray-900">{note.author}</span>
                      <span className="text-sm text-gray-600">
                        {formatDateTime(note.createdAt)}
                      </span>
                    </div>
                    <p className="text-gray-700 text-sm">{note.content}</p>
                  </div>
                ))}
              </div>
            ) : (
              <p className="text-sm text-gray-500">No activity yet</p>
            )}
          </div>
        )}

        {/* Add Note Section */}
        {showAddNote && (
          <div className="border-t border-gray-200 pt-4 mb-4 space-y-3">
            <Textarea
              placeholder="Add a note..."
              value={newNote}
              onChange={(e) => setNewNote(e.target.value)}
              rows={3}
              className="w-full"
            />
            <div className="flex gap-2">
              <Button onClick={handleAddNote} size="sm" disabled={!newNote.trim()}>
                Submit Note
              </Button>
              <Button onClick={() => setShowAddNote(false)} variant="outline" size="sm">
                Cancel
              </Button>
            </div>
          </div>
        )}

        {/* Bottom Actions */}
        <div className="flex flex-wrap items-center justify-between pt-4 border-t border-gray-200 gap-3">
          <Button
            variant="ghost"
            onClick={() => setShowAllActivity(!showAllActivity)}
            className="text-gray-700 hover:text-gray-900"
          >
            {showAllActivity ? (
              <>
                <ChevronUp className="h-4 w-4 mr-2" />
                Hide Activity
              </>
            ) : (
              <>
                <ChevronDown className="h-4 w-4 mr-2" />
                View Activity
              </>
            )}
          </Button>
          <div className="flex gap-2 flex-wrap">
            <Button
              variant="outline"
              onClick={() => setShowAddNote(!showAddNote)}
            >
              Add Comment
            </Button>
            <Button
              onClick={() => onUpload(condition.id)}
              className="bg-red-700 hover:bg-red-800 text-white whitespace-nowrap"
            >
              Add Documents
            </Button>
            {condition.status === 'pending' && condition.documents.length > 0 && (
              <Button
                onClick={() => onStatusChange(condition.id, 'completed')}
                className="bg-green-600 hover:bg-green-700 text-white whitespace-nowrap"
              >
                Mark Complete
              </Button>
            )}
            {condition.status === 'completed' && (
              <Button
                onClick={() => onStatusChange(condition.id, 'pending')}
                variant="outline"
                className="whitespace-nowrap"
              >
                Reopen
              </Button>
            )}
          </div>
        </div>
      </CardContent>
    </Card>
  )
}

export default function DocumentsStep() {
  const {
    activeClientId,
    clients,
    generateConditionsForClient,
    getConditionsForClient,
    getConditionStats,
    addConditionNote,
    addConditionDocument,
    removeConditionDocument,
    updateConditionStatus,
    addToDocumentLibrary,
    getDocumentLibrary,
    removeFromDocumentLibrary
  } = useApplicationStore()

  const [uploadModalOpen, setUploadModalOpen] = useState(false)
  const [selectedConditionId, setSelectedConditionId] = useState<string | null>(null)

  const client = clients[activeClientId]
  const conditions = activeClientId ? getConditionsForClient(activeClientId) : []
  const stats = activeClientId ? getConditionStats(activeClientId) : { total: 0, pending: 0, inProgress: 0, completed: 0, cancelled: 0 }
  const selectedCondition = conditions.find(c => c.id === selectedConditionId)
  const documentLibrary = getDocumentLibrary()

  // Generate conditions when component mounts or client changes
  useEffect(() => {
    if (activeClientId) {
      generateConditionsForClient(activeClientId)
    }
  }, [activeClientId, generateConditionsForClient])

  const handleUpload = (conditionId: string) => {
    setSelectedConditionId(conditionId)
    setUploadModalOpen(true)
  }

  const handleFilesUpload = (files: File[], selectedDocIds: string[]) => {
    if (!selectedConditionId || !activeClientId) return

    const userName = client?.firstName ? `${client.firstName} ${client.lastName}` : 'User'
    const { currentApplicationId } = useApplicationStore.getState()
    
    // Handle new file uploads
    files.forEach((file) => {
      const document: ConditionDocument = {
        id: generateDocumentId(currentApplicationId || undefined),
        name: file.name,
        size: file.size,
        type: file.type,
        uploadedAt: new Date().toISOString(),
        uploadedBy: userName,
        // In a real implementation, you would upload the file to a storage service
        // and store the URL here. For now, we'll store it in memory.
      }
      
      // Add to document library
      addToDocumentLibrary(document)
      
      // Attach to condition
      addConditionDocument(activeClientId, selectedConditionId, document)
    })
    
    // Handle selected existing documents
    selectedDocIds.forEach((docId) => {
      const existingDoc = documentLibrary.find(doc => doc.id === docId)
      if (existingDoc) {
        // Attach existing document to condition
        addConditionDocument(activeClientId, selectedConditionId, existingDoc)
      }
    })
  }

  const handleRemoveDocument = (conditionId: string, documentId: string) => {
    if (activeClientId) {
      removeConditionDocument(activeClientId, conditionId, documentId)
    }
  }

  const handleRemoveFromLibrary = (documentId: string) => {
    // Remove from library and from all conditions that reference it
    removeFromDocumentLibrary(documentId)
    // Also remove from any conditions that have this document
    if (activeClientId) {
      conditions.forEach((condition) => {
        if (condition.documents.some(doc => doc.id === documentId)) {
          removeConditionDocument(activeClientId, condition.id, documentId)
        }
      })
    }
  }

  const handleStatusChange = (conditionId: string, status: 'pending' | 'in_progress' | 'completed') => {
    if (activeClientId) {
      updateConditionStatus(activeClientId, conditionId, status)
    }
  }

  const handleAddNote = (conditionId: string, noteContent: string) => {
    if (activeClientId) {
      const newNote = {
        id: `note-${Date.now()}`,
        content: noteContent,
        author: client?.firstName ? `${client.firstName} ${client.lastName}` : 'User',
        createdAt: new Date().toISOString()
      }
      addConditionNote(activeClientId, conditionId, newNote)
    }
  }

  // Group conditions by category (show all, not just pending)
  const idConditions = conditions.filter((c: Condition) => c.category === 'ID')
  const incomeConditions = conditions.filter((c: Condition) => c.category === 'Income')
  const assetsConditions = conditions.filter((c: Condition) => c.category === 'Assets')
  const propertyConditions = conditions.filter((c: Condition) => c.category === 'Property')
  const creditConditions = conditions.filter((c: Condition) => c.category === 'Credit')

  // Show loading state if no active client
  if (!activeClientId) {
    return (
      <div className="max-w-6xl mx-auto space-y-6">
        <ClientTabs />
        <div className="text-center py-12">
          <p className="text-gray-500">Please select a client to view documents.</p>
        </div>
      </div>
    )
  }

  return (
    <div className="max-w-6xl mx-auto space-y-6">
      {/* Client tabs */}
      <ClientTabs />

      {/* Overview */}
      <Card>
        <CardHeader>
          <CardTitle>Required Documentation</CardTitle>
          <CardDescription>
            Based on your application, we need the following documents from {client?.firstName || 'you'}
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-3 gap-4">
            <div className="text-center">
              <div className="text-3xl font-bold text-gray-900">{stats.total}</div>
              <div className="text-sm text-gray-500">Total Required</div>
            </div>
            <div className="text-center">
              <div className="text-3xl font-bold text-orange-600">{stats.pending}</div>
              <div className="text-sm text-gray-500">Pending</div>
            </div>
            <div className="text-center">
              <div className="text-3xl font-bold text-green-600">{stats.completed}</div>
              <div className="text-sm text-gray-500">Completed</div>
            </div>
          </div>
        </CardContent>
      </Card>

      {conditions.length === 0 ? (
        <Alert>
          <FileText className="h-4 w-4" />
          <AlertDescription>
            No documents required yet. Complete the previous steps to generate your document checklist.
          </AlertDescription>
        </Alert>
      ) : (
        <Tabs defaultValue="id" className="w-full">
          <TabsList className="grid w-full grid-cols-5">
            <TabsTrigger value="id">
              ID ({idConditions.length})
            </TabsTrigger>
            <TabsTrigger value="income">
              Income ({incomeConditions.length})
            </TabsTrigger>
            <TabsTrigger value="assets">
              Assets ({assetsConditions.length})
            </TabsTrigger>
            <TabsTrigger value="property">
              Property ({propertyConditions.length})
            </TabsTrigger>
            <TabsTrigger value="credit">
              Credit ({creditConditions.length})
            </TabsTrigger>
          </TabsList>

          <TabsContent value="id" className="mt-6">
            {idConditions.length > 0 ? (
              idConditions.map((condition: Condition) => (
                <ConditionCard
                  key={condition.id}
                  condition={condition}
                  onUpload={handleUpload}
                  onAddNote={handleAddNote}
                  onRemoveDocument={handleRemoveDocument}
                  onStatusChange={handleStatusChange}
                />
              ))
            ) : (
              <div className="text-center py-12 text-gray-500">
                No ID documents required
              </div>
            )}
          </TabsContent>

          <TabsContent value="income" className="mt-6">
            {incomeConditions.length > 0 ? (
              incomeConditions.map((condition: Condition) => (
                <ConditionCard
                  key={condition.id}
                  condition={condition}
                  onUpload={handleUpload}
                  onAddNote={handleAddNote}
                  onRemoveDocument={handleRemoveDocument}
                  onStatusChange={handleStatusChange}
                />
              ))
            ) : (
              <div className="text-center py-12 text-gray-500">
                No income documents required
              </div>
            )}
          </TabsContent>

          <TabsContent value="assets" className="mt-6">
            {assetsConditions.length > 0 ? (
              assetsConditions.map((condition: Condition) => (
                <ConditionCard
                  key={condition.id}
                  condition={condition}
                  onUpload={handleUpload}
                  onAddNote={handleAddNote}
                  onRemoveDocument={handleRemoveDocument}
                  onStatusChange={handleStatusChange}
                />
              ))
            ) : (
              <div className="text-center py-12 text-gray-500">
                No asset documents required
              </div>
            )}
          </TabsContent>

          <TabsContent value="property" className="mt-6">
            {propertyConditions.length > 0 ? (
              propertyConditions.map((condition: Condition) => (
                <ConditionCard
                  key={condition.id}
                  condition={condition}
                  onUpload={handleUpload}
                  onAddNote={handleAddNote}
                  onRemoveDocument={handleRemoveDocument}
                  onStatusChange={handleStatusChange}
                />
              ))
            ) : (
              <div className="text-center py-12 text-gray-500">
                No property documents required
              </div>
            )}
          </TabsContent>

          <TabsContent value="credit" className="mt-6">
            {creditConditions.length > 0 ? (
              creditConditions.map((condition: Condition) => (
                <ConditionCard
                  key={condition.id}
                  condition={condition}
                  onUpload={handleUpload}
                  onAddNote={handleAddNote}
                  onRemoveDocument={handleRemoveDocument}
                  onStatusChange={handleStatusChange}
                />
              ))
            ) : (
              <div className="text-center py-12 text-gray-500">
                No credit documents required
              </div>
            )}
          </TabsContent>
        </Tabs>
      )}

      {/* Document Upload Modal */}
      <DocumentUploadModal
        open={uploadModalOpen}
        onClose={() => {
          setUploadModalOpen(false)
          setSelectedConditionId(null)
        }}
        onUpload={handleFilesUpload}
        conditionTitle={selectedCondition?.title || ''}
        existingDocuments={documentLibrary}
        onRemoveFromLibrary={handleRemoveFromLibrary}
      />
    </div>
  )
}

// src/lib/components/steps/DocumentsStep.svelte
<script lang="ts">
	import { Card, CardHeader, CardTitle, CardContent, CardDescription } from '$lib/components/ui';
	import { Button, Badge, Textarea } from '$lib/components/ui';
	import { Upload, FileText, CheckCircle, AlertCircle, Trash2, CreditCard, DollarSign, Building2, Home, FileCheck, MessageSquare, History, ChevronDown, ChevronUp } from 'lucide-svelte';
	import ClientTabs from './ClientTabs.svelte';
	import { applicationStore, activeClientId, activeClientData, activeEmploymentData } from '$lib/stores/application';
	import type { DocumentRecord, DocumentHistoryEntry } from '$lib/stores/application';
	import { generateConditions } from '$lib/conditions';
	import type { Condition } from '$lib/types/conditions';
	import { get } from 'svelte/store';
	
	let expandedConditions = $state<Set<string>>(new Set());
	let showHistoryFor = $state<string | null>(null);
	let noteInputs = $state<Record<string, string>>({});
	
	// Generate document requirements based on application data
	let documentRequirements = $derived.by(() => {
		const client = $activeClientData;
		const employmentRecords = $activeEmploymentData?.records || [];
		const assets = $applicationStore.assetsData[$activeClientId]?.records || [];
		
		if (!client || !client.firstName) {
			return [];
		}
		
		// Generate conditions using the condition generator
		const conditions = generateConditions({
			clientId: $activeClientId,
			client,
			employmentData: employmentRecords,
			assets
		});
		
		// Group conditions by category and convert to document requirements
		return conditions.map(condition => ({
			id: condition.id,
			title: condition.title,
			description: condition.description,
			category: condition.category,
			priority: condition.priority,
			condition: condition
		}));
	});
	
	// Group documents by category
	let documentsByCategory = $derived.by(() => {
		const grouped: Record<string, typeof documentRequirements> = {};
		for (const doc of documentRequirements) {
			if (!grouped[doc.category]) {
				grouped[doc.category] = [];
			}
			grouped[doc.category].push(doc);
		}
		return grouped;
	});
	
	function getDocumentsForCondition(conditionId: string): DocumentRecord[] {
		const docs = $applicationStore.documentsData[$activeClientId]?.documents || [];
		// Support both new structure (conditionId) and old structure (id === conditionId)
		return docs.filter(d => (d.conditionId || d.id) === conditionId).sort((a, b) => {
			// Sort by version (newest first) or upload date
			if (a.version && b.version) return b.version - a.version;
			if (a.uploadedAt && b.uploadedAt) return new Date(b.uploadedAt).getTime() - new Date(a.uploadedAt).getTime();
			return 0;
		});
	}
	
	function getConditionHistory(conditionId: string): DocumentHistoryEntry[] {
		const history = $applicationStore.documentsData[$activeClientId]?.history || [];
		// Get history for this condition (by conditionId or documentId)
		return history
			.filter(h => {
				const docs = getDocumentsForCondition(conditionId);
				return docs.some(d => d.id === h.documentId) || h.documentId === conditionId;
			})
			.sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime());
	}
	
	function getConditionNotes(conditionId: string): string[] {
		return $applicationStore.documentsData[$activeClientId]?.conditionNotes?.[conditionId] || [];
	}
	
	function toggleCondition(conditionId: string) {
		if (expandedConditions.has(conditionId)) {
			expandedConditions.delete(conditionId);
		} else {
			expandedConditions.add(conditionId);
		}
		expandedConditions = new Set(expandedConditions);
	}
	
	function toggleHistory(conditionId: string) {
		showHistoryFor = showHistoryFor === conditionId ? null : conditionId;
	}
	
	function addNote(conditionId: string) {
		const note = noteInputs[conditionId]?.trim();
		if (note) {
			applicationStore.addConditionNote($activeClientId, conditionId, note);
			noteInputs[conditionId] = '';
		}
	}
	
	function handleFileUpload(conditionId: string, event: Event) {
		const input = event.target as HTMLInputElement;
		const files = input.files;
		if (files && files.length > 0) {
			// Create a document type based on condition category
			const categoryMap: Record<string, DocumentRecord['type']> = {
				'ID': 'id',
				'Income': 'income',
				'Assets': 'bank',
				'Property': 'employment',
				'Credit': 'employment'
			};
			const type = categoryMap[documentRequirements.find(d => d.id === conditionId)?.category || 'Income'] || 'income';
			
			// Upload each file
			for (let i = 0; i < files.length; i++) {
				const file = files[i];
				applicationStore.uploadDocument($activeClientId, conditionId, type, file);
			}
		}
		// Reset input so same file can be selected again
		input.value = '';
	}
	
	function handleRemoveDocument(documentId: string) {
		applicationStore.removeDocument($activeClientId, documentId);
	}
	
	function formatFileSize(bytes: number): string {
		if (bytes < 1024) return bytes + ' B';
		if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(1) + ' KB';
		return (bytes / (1024 * 1024)).toFixed(1) + ' MB';
	}
	
	function getCategoryIcon(category: string) {
		switch (category) {
			case 'ID': return CreditCard;
			case 'Income': return DollarSign;
			case 'Assets': return Building2;
			case 'Property': return Home;
			case 'Credit': return FileCheck;
			default: return FileText;
		}
	}
	
	function getPriorityColor(priority: string) {
		switch (priority) {
			case 'high': return 'text-destructive';
			case 'medium': return 'text-warning';
			case 'low': return 'text-muted-foreground';
			default: return 'text-muted-foreground';
		}
	}
</script>

<div class="max-w-4xl mx-auto space-y-6">
	<ClientTabs />
	
	{#if documentRequirements.length === 0}
		<Card>
			<CardContent class="py-12">
				<div class="text-center space-y-4">
					<AlertCircle class="h-12 w-12 text-muted-foreground mx-auto" />
					<div>
						<h3 class="font-medium text-lg">No Documents Required Yet</h3>
						<p class="text-muted-foreground text-sm">
							Complete the previous steps (Client Info, Employment, Income) to see required documents.
						</p>
					</div>
				</div>
			</CardContent>
		</Card>
	{:else}
		{#each Object.entries(documentsByCategory) as [category, docs]}
			{@const CategoryIcon = getCategoryIcon(category)}
	<Card>
		<CardHeader>
					<div class="flex items-center gap-2">
						<CategoryIcon class="h-5 w-5 text-primary" />
						<CardTitle>{category} Documents</CardTitle>
					</div>
					<CardDescription>
						{docs.length} document{docs.length !== 1 ? 's' : ''} required
					</CardDescription>
		</CardHeader>
		<CardContent class="space-y-4">
					{#each docs as doc}
						{@const uploadedDocs = getDocumentsForCondition(doc.id)}
						{@const conditionNotes = getConditionNotes(doc.id)}
						{@const history = getConditionHistory(doc.id)}
						{@const isExpanded = expandedConditions.has(doc.id)}
						<div class="rounded-lg border bg-card">
							<!-- Condition Header -->
							<div class="flex items-center justify-between p-4 hover:bg-muted/50 transition-colors">
								<div class="flex items-center gap-4 flex-1">
									<div class="h-10 w-10 rounded-lg bg-muted flex items-center justify-center shrink-0">
							<FileText class="h-5 w-5 text-muted-foreground" />
						</div>
									<div class="flex-1 min-w-0">
										<div class="flex items-center gap-2">
											<div class="font-medium">{doc.title}</div>
											<Badge variant={doc.priority === 'high' ? 'destructive' : doc.priority === 'medium' ? 'default' : 'secondary'} class="text-xs">
												{doc.priority}
											</Badge>
											{#if uploadedDocs.length > 0}
												<Badge variant="outline" class="text-xs">
													{uploadedDocs.length} file{uploadedDocs.length !== 1 ? 's' : ''}
												</Badge>
											{/if}
										</div>
										<div class="text-sm text-muted-foreground mt-1">{doc.description}</div>
						</div>
					</div>
								<div class="flex items-center gap-2 shrink-0">
									{#if uploadedDocs.length > 0}
										<span class="flex items-center gap-1 text-sm text-success">
											<CheckCircle class="h-4 w-4" />
											Uploaded
										</span>
									{:else}
							<span class="flex items-center gap-1 text-sm text-muted-foreground">
								<AlertCircle class="h-4 w-4" />
								Required
							</span>
									{/if}
									<Button 
										variant="ghost" 
										size="sm" 
										onclick={() => toggleCondition(doc.id)}
									>
										{#if isExpanded}
											<ChevronUp class="h-4 w-4" />
						{:else}
											<ChevronDown class="h-4 w-4" />
						{/if}
						</Button>
					</div>
							</div>
							
							<!-- Expanded Content -->
							{#if isExpanded}
								<div class="border-t p-4 space-y-4">
									<!-- File Upload -->
									<div>
										<label>
											<Button variant="outline" size="sm" class="gap-2 cursor-pointer" as="span">
												<Upload class="h-4 w-4" />
												Upload File{uploadedDocs.length > 0 ? ' (Additional)' : ''}
											</Button>
											<input
												type="file"
												class="hidden"
												accept=".pdf,.jpg,.jpeg,.png,.doc,.docx"
												multiple
												onchange={(e) => handleFileUpload(doc.id, e)}
											/>
										</label>
									</div>
									
									<!-- Uploaded Files -->
									{#if uploadedDocs.length > 0}
										<div class="space-y-2">
											<div class="text-sm font-medium">Uploaded Files:</div>
											{#each uploadedDocs as uploadedDoc}
												<div class="flex items-center justify-between p-2 rounded bg-muted/50">
													<div class="flex items-center gap-2 flex-1">
														<FileText class="h-4 w-4 text-muted-foreground" />
														<div class="flex-1 min-w-0">
															<div class="text-sm font-medium truncate">{uploadedDoc.filename}</div>
															<div class="text-xs text-muted-foreground">
																{formatFileSize(uploadedDoc.sizeBytes)} • 
																{uploadedDoc.uploadedAt ? new Date(uploadedDoc.uploadedAt).toLocaleDateString() : 'Unknown date'}
																{#if uploadedDoc.version && uploadedDoc.version > 1}
																	• Version {uploadedDoc.version}
																{/if}
															</div>
														</div>
													</div>
													<Button 
														variant="ghost" 
														size="sm" 
														class="gap-2 text-destructive hover:text-destructive"
														onclick={() => handleRemoveDocument(uploadedDoc.id)}
													>
														<Trash2 class="h-4 w-4" />
													</Button>
												</div>
											{/each}
										</div>
									{/if}
									
									<!-- Notes Section -->
									<div class="space-y-2">
										<div class="flex items-center justify-between">
											<div class="text-sm font-medium">Notes & Comments:</div>
											<Button 
												variant="ghost" 
												size="sm" 
												onclick={() => toggleHistory(doc.id)}
												class="gap-2"
											>
												<History class="h-4 w-4" />
												History ({history.length})
											</Button>
										</div>
										
										<!-- Add Note -->
										<div class="flex gap-2">
											<Textarea
												placeholder="Add a note or comment about this document..."
												value={noteInputs[doc.id] || ''}
												oninput={(e) => noteInputs[doc.id] = e.currentTarget.value}
												class="min-h-[60px]"
											/>
											<Button 
												size="sm" 
												onclick={() => addNote(doc.id)}
												disabled={!noteInputs[doc.id]?.trim()}
											>
												<MessageSquare class="h-4 w-4" />
											</Button>
										</div>
										
										<!-- Display Notes -->
										{#if conditionNotes.length > 0}
											<div class="space-y-1">
												{#each conditionNotes as note}
													<div class="text-sm p-2 rounded bg-muted/30">
														{note}
													</div>
												{/each}
											</div>
										{/if}
										
										<!-- History -->
										{#if showHistoryFor === doc.id && history.length > 0}
											<div class="mt-4 space-y-2 border-t pt-4">
												<div class="text-sm font-medium">History:</div>
												<div class="space-y-2 max-h-60 overflow-y-auto">
													{#each history as entry}
														<div class="text-xs p-2 rounded bg-muted/30">
															<div class="flex items-center justify-between">
																<span class="font-medium">{entry.action}</span>
																<span class="text-muted-foreground">
																	{new Date(entry.timestamp).toLocaleString()}
																</span>
															</div>
															{#if entry.filename}
																<div class="text-muted-foreground mt-1">File: {entry.filename}</div>
															{/if}
															{#if entry.note}
																<div class="text-muted-foreground mt-1">Note: {entry.note}</div>
															{/if}
															<div class="text-muted-foreground mt-1">By: {entry.user}</div>
														</div>
													{/each}
												</div>
											</div>
										{/if}
									</div>
								</div>
							{/if}
				</div>
			{/each}
		</CardContent>
	</Card>
		{/each}
	{/if}
</div>
